IF
!Exists("balth") 
Global("BalthazarFights","GLOBAL",1)
Global("HadBhaal25Dream5","GLOBAL",0)
OR(2)
!Global("AcceptIlmater","GLOBAL",1)
!InParty("lrirenic")  
OR(2)
!Global("AcceptIlmater","GLOBAL",2)
!InParty("lrirenic") 
OR(2)
!Global("lrbalt","GLOBAL",1)
!InParty("lrirenic")  
THEN
RESPONSE #100
ClearAllActions()
SetGlobal("HadBhaal25Dream5","GLOBAL",1)
StartCutSceneMode()
StartCutScene("cut243a")
END

